### ISSUE TITLE
Weird upper cavern level generation with the Z-level mod.

### ISSUE THREAD

**Issue by Superfly-Johnson** [emipa606/CaveBiome#1]
https://i.imgur.com/faHZgP5.jpg Very weird layer generation with the Z-level mod with an up ladder. Instead of generating a new layer it basically duplicates the below layer with the same generation and all and makes no flooring.

https://i.imgur.com/F6XvgvY.jpg Here's the first floor. Somehow the ore generation differs for new layers, but not the cavern generation. Down-layers aren't affected, digging down generates entirely new caves.

You can also notice the lighting is messed up when digging up,.

How to reproduce: Using the Z-level mod make a ladder up, and "go up" with a pawn. You'll create a duplicate of the lower layer, with the main difference between ore placement and a lack of flooring.

**Comment by emipa606** [comment]
Oh, you meant that you are using the cavebiome mod? I did not get that from you report on the discord.

**Comment by emipa606** [comment]
Issue is not with this mod but the default workings of the z-levels mod.
